### ISSUE TITLE
OpenCR can't read motor encoder

### ISSUE THREAD

**Issue by ludusrusso** [ROBOTIS-GIT/turtlebot3#162]
Hi,
my turtlebot works great, but it can't read the motor encorders, while is able to control them very well.

Here the motor info:
 - firmware version 41
 - protocol 2.0

The topic `/sensor_state` is never published, while topic `joint_states` return the same value:

```
header: 
  seq: 759
  stamp: 
    secs: 1522323390
    nsecs: 940208339
  frame_id: base_link
name: ['wheel_left_joint', 'wheel_right_joint']
position: [0.0, 0.0]
velocity: [0.0, 0.0]
effort: [7.335467576660691e+21, 143.15293884277344]

```
