### ISSUE TITLE
some lds scan ranges data don't exist 

### ISSUE THREAD

**Issue by EndlessLoops** [ROBOTIS-GIT/turtlebot3#404]
ISSUE TEMPLATE ver. 0.2.0

1. Which TurtleBot3 you have?

    - [*] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [*] Raspberry Pi 3
    - [ ] Intel Joule 570x
    - [ ] etc (PLEASE, WRITE DOWN YOUR SBC HERE)

3. Which OS you installed in SBC?

    - [ ] Ubuntu MATE 16.04 or later
    - [ ] Raspbian
    - [*] lubuntu 1604

4. Which OS you installed in Remote PC?

    - [*] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Linux Mint 18.x
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

5. Write down software version and firmware version

    - Software version: []
    - Firmware version: [1.2.3]
 
6. Write down the commands you used in order

    - HERE
 
7. Copy and Paste your error message on terminal

real tb3 : /scan
```
    ---
header:
  seq: 6636
  stamp:
    secs: 1555483299
    nsecs: 661919802
  frame_id: "base_scan"
angle_min: 0.0
angle_max: 6.26573181152
angle_increment: 0.0174532923847
time_increment: 2.98699997074e-05
scan_time: 0.0
range_min: 0.119999997318
range_max: 3.5
ranges: [1.753000020980835, 1.7630000114440918, 1.7769999504089355, 1.7690000534057617, 1.753999948501587, 1.7660000324249268, 1.7640000581741333, 1.7100000381469727, 1.8270000219345093, 1.8660000562667847, 1.8589999675750732, 1.8550000190734863, 1.8580000400543213, 1.8760000467300415, 1.8680000305175781, 1.8880000114440918, 1.8919999599456787, 1.9040000438690186, 1.9049999713897705, 0.0, 0.0, 0.0, 0.0, 0.0, 1.562999963760376, 1.61899995803833, 0.0, 1.4579999446868896, 1.3240000009536743, 1.3270000219345093, 1.3200000524520874, 1.6829999685287476, 1.6859999895095825, 1.7300000190734863, 0.0, 0.0, 1.430999994277954, 1.440999984741211, 1.5180000066757202, 0.0, 0.0, 2.2079999446868896, 0.0, 0.0, 0.0, 2.5339999198913574, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.5859999656677246, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.100000023841858, 0.9559999704360962, 0.9559999704360962, 0.8899999856948853, 0.8790000081062317, 0.6439999938011169, 0.75, 0.7160000205039978, 0.6549999713897705, 0.6179999709129333, 0.593999981880188, 0.5630000233650208, 0.5370000004768372, 0.0, 0.0, 0.0, 0.0, 0.44999998807907104, 0.0, 0.0, 0.0, 0.0, 0.296999990940094, 0.3019999861717224, 0.3070000112056732, 0.2939999997615814, 0.28700000047683716, 0.2840000092983246, 0.2720000147819519, 0.2680000066757202, 0.2619999945163727, 0.257999986410141, 0.2529999911785126, 0.24500000476837158, 0.24300000071525574, 0.23899999260902405, 0.23499999940395355, 0.23100000619888306, 0.22699999809265137, 0.22200000286102295, 0.21899999678134918, 0.21799999475479126, 0.2150000035762787, 0.21199999749660492, 0.20900000631809235, 0.20600000023841858, 0.20399999618530273, 0.20200000703334808, 0.20000000298023224, 0.1979999989271164, 0.19599999487400055, 0.1940000057220459, 0.19200000166893005, 0.19099999964237213, 0.1899999976158142, 0.18799999356269836, 0.18700000643730164, 0.1860000044107437, 0.1850000023841858, 0.18400000035762787, 0.18299999833106995, 0.18199999630451202, 0.1809999942779541, 0.18000000715255737, 0.17900000512599945, 0.17800000309944153, 0.1770000010728836, 0.1770000010728836, 0.17599999904632568, 0.17599999904632568, 0.17499999701976776, 0.17499999701976776, 0.17399999499320984, 0.17399999499320984, 0.17399999499320984, 0.17399999499320984, 0.17399999499320984, 0.17399999499320984, 0.17399999499320984, 0.17399999499320984, 0.17299999296665192, 0.17399999499320984, 0.17399999499320984, 0.17299999296665192, 0.17499999701976776, 0.17399999499320984, 0.17499999701976776, 0.17599999904632568, 0.17599999904632568, 0.17599999904632568, 0.1770000010728836, 0.17800000309944153, 0.17900000512599945, 0.17900000512599945, 0.18000000715255737, 0.18000000715255737, 0.1809999942779541, 0.18299999833106995, 0.18299999833106995, 0.1850000023841858, 0.1860000044107437, 0.18799999356269836, 0.1899999976158142, 0.19300000369548798, 0.19499999284744263, 0.19200000166893005, 0.1940000057220459, 0.19499999284744263, 0.19699999690055847, 0.19900000095367432, 0.20000000298023224, 0.20200000703334808, 0.20399999618530273, 0.2070000022649765, 0.20999999344348907, 0.21299999952316284, 0.2150000035762787, 0.21799999475479126, 0.22100000083446503, 0.22499999403953552, 0.2280000001192093, 0.23100000619888306, 0.23399999737739563, 0.2150000035762787, 0.2370000034570694, 0.2540000081062317, 0.25600001215934753, 0.257999986410141, 0.2630000114440918, 0.26600000262260437, 0.2709999978542328, 0.2770000100135803, 0.2809999883174896, 0.28700000047683716, 0.0, 0.0, 0.29600000381469727, 0.3009999990463257, 0.33799999952316284, 0.0, 0.0, 0.0, 0.0, 0.0, 0.38999998569488525, 0.0, 0.0, 0.0, 0.0, 0.0, 0.515999972820282, 0.5230000019073486, 0.5460000038146973, 0.5789999961853027, 0.6010000109672546, 0.628000020980835, 0.6850000023841858, 0.0, 0.7770000100135803, 0.7850000262260437, 0.0, 0.0, 0.0, 1.125, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.243000030517578, 2.130000114440918, 2.2100000381469727, 2.0510001182556152, 2.0350000858306885, 1.9589999914169312, 1.9390000104904175, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.715000033378601, 1.7730000019073486, 1.7719999551773071, 1.7680000066757202, 1.7610000371932983]
intensities: [1735.0, 2096.0, 1120.0, 1132.0, 1125.0, 905.0, 449.0, 589.0, 606.0, 554.0, 526.0, 476.0, 770.0, 694.0, 677.0, 426.0, 414.0, 415.0, 399.0, 66.0, 67.0, 48.0, 58.0, 0.0, 252.0, 275.0, 60.0, 269.0, 598.0, 527.0, 515.0, 213.0, 236.0, 150.0, 132.0, 107.0, 506.0, 361.0, 102.0, 185.0, 175.0, 102.0, 128.0, 131.0, 135.0, 128.0, 173.0, 111.0, 0.0, 119.0, 129.0, 173.0, 119.0, 120.0, 131.0, 85.0, 92.0, 112.0, 73.0, 0.0, 0.0, 0.0, 0.0, 71.0, 60.0, 0.0, 0.0, 72.0, 74.0, 82.0, 92.0, 90.0, 73.0, 82.0, 95.0, 115.0, 131.0, 166.0, 165.0, 165.0, 164.0, 80.0, 154.0, 140.0, 0.0, 39.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 41.0, 54.0, 93.0, 66.0, 123.0, 122.0, 245.0, 519.0, 2278.0, 2549.0, 283.0, 464.0, 794.0, 835.0, 1183.0, 1078.0, 1186.0, 1583.0, 0.0, 0.0, 0.0, 0.0, 1314.0, 45.0, 0.0, 44.0, 45.0, 114.0, 5571.0, 5182.0, 4518.0, 5924.0, 4083.0, 4714.0, 4603.0, 5250.0, 4511.0, 4558.0, 6641.0, 6689.0, 8421.0, 7597.0, 6936.0, 6736.0, 6353.0, 7145.0, 6844.0, 6692.0, 8072.0, 7730.0, 7338.0, 7127.0, 7543.0, 7747.0, 7314.0, 7375.0, 7660.0, 8198.0, 7696.0, 8130.0, 7439.0, 8287.0, 8440.0, 8003.0, 7627.0, 7535.0, 8317.0, 8531.0, 8440.0, 8002.0, 8879.0, 7912.0, 8103.0, 7899.0, 8108.0, 8582.0, 8087.0, 8585.0, 8204.0, 8565.0, 8129.0, 8703.0, 8374.0, 8558.0, 7723.0, 8344.0, 8001.0, 6929.0, 11043.0, 7967.0, 8250.0, 7992.0, 8892.0, 8201.0, 7989.0, 8019.0, 8046.0, 8099.0, 8243.0, 7355.0, 7258.0, 8608.0, 7773.0, 7920.0, 8078.0, 9370.0, 9556.0, 8357.0, 7723.0, 2941.0, 2466.0, 2230.0, 2314.0, 1959.0, 1987.0, 1911.0, 1723.0, 1759.0, 1710.0, 1340.0, 1262.0, 1309.0, 988.0, 1038.0, 788.0, 845.0, 776.0, 476.0, 1163.0, 6018.0, 6389.0, 394.0, 244.0, 280.0, 366.0, 242.0, 279.0, 388.0, 236.0, 100.0, 61.0, 4187.0, 4616.0, 3656.0, 0.0, 72.0, 50.0, 0.0, 51.0, 127.0, 102.0, 0.0, 0.0, 0.0, 0.0, 1611.0, 1435.0, 860.0, 1211.0, 1047.0, 792.0, 694.0, 613.0, 421.0, 2720.0, 0.0, 40.0, 0.0, 111.0, 109.0, 0.0, 65.0, 0.0, 0.0, 0.0, 73.0, 109.0, 0.0, 0.0, 76.0, 0.0, 74.0, 80.0, 94.0, 79.0, 63.0, 73.0, 70.0, 0.0, 76.0, 0.0, 56.0, 53.0, 49.0, 57.0, 89.0, 49.0, 0.0, 0.0, 33.0, 0.0, 0.0, 0.0, 0.0, 39.0, 0.0, 0.0, 0.0, 0.0, 45.0, 0.0, 65.0, 116.0, 85.0, 67.0, 158.0, 129.0, 109.0, 103.0, 51.0, 99.0, 81.0, 76.0, 80.0, 59.0, 70.0, 53.0, 138.0, 122.0, 238.0, 111.0, 240.0, 289.0, 289.0, 309.0, 106.0, 101.0, 73.0, 92.0, 86.0, 81.0, 75.0, 73.0, 114.0, 119.0, 59.0, 58.0, 56.0, 0.0, 66.0, 0.0, 132.0, 0.0, 70.0, 122.0, 112.0, 2384.0, 146.0, 64.0, 73.0, 247.0, 577.0, 595.0, 650.0, 1864.0]
---
```
  tb3 in gazebo :   /scan

```
header:
  seq: 40
  stamp:
    secs: 2365
    nsecs: 742000000
  frame_id: "base_scan"
angle_min: 0.0
angle_max: 6.28318977356
angle_increment: 0.0175019223243
time_increment: 0.0
scan_time: 0.0
range_min: 0.119999997318
range_max: 3.5
ranges: [0.44827720522880554, 0.4582839906215668, 0.4640919864177704, 0.4477328360080719, 0.45736950635910034, 0.4394715428352356, 0.4652138650417328, 0.4459340572357178, 0.43057891726493835, 0.45369789004325867, 0.4548622965812683, 0.4590340852737427, 0.44497933983802795, 0.4591759443283081, 0.44699692726135254, 0.4599118232727051, 0.45958006381988525, 0.4587402641773224, 0.45869582891464233, 0.4747074246406555, 0.45813313126564026, 0.48715636134147644, 0.4536595642566681, 0.4774110019207001, 0.49255263805389404, 0.4667488932609558, 0.48079487681388855, 0.4821007251739502, 0.507922351360321, 0.4994967579841614, 0.49763223528862, 0.4803834855556488, 0.48592013120651245, 0.4702204465866089, 0.4619605839252472, 0.46753498911857605, 0.4280758500099182, 0.39460620284080505, 0.41343626379966736, 0.40444788336753845, 0.40282806754112244, 0.3920854926109314, 0.37215349078178406, 0.3650938868522644, 0.36306795477867126, 0.3626515865325928, 0.3409230411052704, 0.31714245676994324, 0.3149515986442566, 0.3259260058403015, 0.30524685978889465, 0.2949964702129364, 0.2946590483188629, 0.28673234581947327, 0.3051193356513977, 0.2878147065639496, 0.3057186007499695, 0.2865361273288727, 0.27921080589294434, 0.2772280275821686, 0.2838069796562195, 0.29015904664993286, 0.2890915870666504, 0.3181929886341095, 0.3121073246002197, 0.31884029507637024, 0.33169859647750854, 0.3554460108280182, 0.3430016338825226, 0.3711637258529663, 0.3653543293476105, 0.4054887890815735, 0.40375396609306335, 0.40452075004577637, 0.4345659911632538, 0.46694573760032654, 0.48884451389312744, 0.5098983645439148, 0.5150248408317566, 0.8281859159469604, 0.8480932712554932, 0.8297992944717407, 0.8223873972892761, 0.8438172340393066, 0.8221734762191772, 0.8122881054878235, 0.828054666519165, 0.8224027156829834, 0.869838535785675, 0.982361376285553, 1.12705659866333, 1.1238511800765991, 1.115705966949463, 1.1133770942687988, 1.1123089790344238, 1.1197513341903687, 1.1103450059890747, 1.1046897172927856, 1.122962236404419, 1.1061080694198608, 1.1036593914031982, 1.1236364841461182, 1.1033563613891602, 1.129144549369812, 1.1319133043289185, 1.1248958110809326, 1.1311522722244263, 1.122318983078003, 1.1257069110870361, 0.8079441785812378, 0.7674497365951538, 0.7340628504753113, 0.6780580282211304, 0.6518617272377014, 0.5939728617668152, 0.5846613645553589, 0.5534825921058655, 0.552300214767456, 0.5530908703804016, 0.567781388759613, 0.5771212577819824, 0.5662508010864258, 0.5897915959358215, 0.5853532552719116, 0.5831209421157837, 0.5975819826126099, 0.6006166338920593, 0.6146995425224304, 0.6156364679336548, 0.6286433935165405, 0.6345809698104858, 0.6346953511238098, 0.6469855904579163, 0.6563729643821716, 0.3124064803123474, 0.2956368625164032, 0.2984844148159027, 0.31866517663002014, 0.3162747323513031, 0.3163493573665619, 0.3225419819355011, 0.34783193469047546, 0.345410019159317, 0.3389263153076172, 0.3533487319946289, 0.3729209303855896, 0.36048686504364014, 0.3816492259502411, 0.3821605145931244, 0.3961567282676697, 0.39613792300224304, 0.4216547906398773, 0.44022640585899353, 0.43484243750572205, 0.45836344361305237, 0.4599822461605072, 0.478753000497818, 0.5001692771911621, 0.5229489207267761, 0.529901385307312, 0.547454297542572, 0.5676767826080322, 0.5856314301490784, 0.6280413866043091, 0.6357897520065308, 0.658610463142395, 0.7217093706130981, 0.730991780757904, 0.7787924408912659, 1.7567977905273438, 1.7518101930618286, 1.7213492393493652, 1.7303087711334229, 1.709863543510437, 1.6936960220336914, 1.701119065284729, 1.6991456747055054, 1.1886332035064697, 1.3438007831573486, 1.3891478776931763, 1.4049396514892578, 1.3949029445648193, 1.4045016765594482, 1.4005762338638306, 1.3856427669525146, 1.381386637687683, 1.3912607431411743, 1.390447735786438, 1.401857852935791, 1.3965965509414673, 1.3837225437164307, 1.3920882940292358, 1.1080853939056396, 1.1011089086532593, 1.0964711904525757, 1.115774393081665, 1.1334325075149536, 1.1192517280578613, 1.1389557123184204, 1.137822151184082, 1.1569766998291016, 1.1490145921707153, 1.1596547365188599, 1.1580102443695068, 1.163812518119812, 1.1950092315673828, 1.1684849262237549, 1.173210859298706, 1.1976600885391235, 1.1886920928955078, 1.2005834579467773, 1.2146399021148682, 1.220023512840271, 1.252066969871521, 1.2497414350509644, 1.2540837526321411, 1.2617595195770264, 1.2777700424194336, 1.3134925365447998, 1.6594877243041992, 1.695944905281067, 1.700512409210205, 2.0198307037353516, 2.038698434829712, 2.084359645843506, 2.0813100337982178, 2.0522754192352295, 2.006474733352661, 1.9627608060836792, 1.9303901195526123, 1.8835748434066772, 1.4919532537460327, 1.5306586027145386, 1.56346595287323, 1.567909836769104, 1.6111669540405273, 1.6566088199615479, 1.6895596981048584, 1.6752996444702148, 1.6653481721878052, 1.2960091829299927, 1.270345687866211, 1.267796277999878, 1.2459568977355957, 1.227776050567627, 1.2220232486724854, 1.1978920698165894, 1.2063511610031128, 1.176568627357483, 1.1609916687011719, 1.1622328758239746, 1.1424566507339478, 1.4440886974334717, 1.4594743251800537, 1.4276419878005981, 1.4314029216766357, 2.028099298477173, 1.998038411140442, 1.9993927478790283, 1.9856818914413452, 1.6593581438064575, 1.6690646409988403, 1.647043228149414, 1.6425273418426514, 1.649145483970642, 1.642504096031189, 1.0578892230987549, 1.2201100587844849, 1.3511556386947632, 1.3372058868408203, 1.3092597723007202, 1.349865198135376, 1.3178929090499878, 1.322312593460083, 1.3173131942749023, 1.3245009183883667, 1.3394559621810913, 1.3391714096069336, 1.3321495056152344, 1.324387788772583, 1.325821876525879, 1.6154175996780396, 1.623032569885254, 1.6384211778640747, 1.6314475536346436, 1.0189900398254395, 1.027805209159851, 1.0434181690216064, 1.0191066265106201, 0.7060640454292297, 0.6364364624023438, 0.6165189743041992, 0.5779566168785095, 0.5568653345108032, 0.4869186580181122, 0.5204829573631287, 0.48325133323669434, 0.4384918808937073, 0.42225560545921326, 0.4176681935787201, 0.40277090668678284, 0.3762911856174469, 0.37348610162734985, 0.34593912959098816, 0.3197956681251526, 0.3267335593700409, 0.3291510343551636, 0.3339046835899353, 0.3210858106613159, 0.3005746603012085, 0.3083800673484802, 0.2863149046897888, 0.2757044732570648, 0.27746039628982544, 0.25625377893447876, 0.2826915383338928, 0.25897425413131714, 0.2572578489780426, 0.2678278982639313, 0.23144809901714325, 0.22456254065036774, 0.23655371367931366, 0.21577702462673187, 0.21470239758491516, 0.20064517855644226, 0.23303081095218658, 0.2245444655418396, 0.22029273211956024, 0.20535698533058167, 0.1788315773010254, 0.19403477013111115, 0.19839535653591156, 0.1879885047674179, 0.19192487001419067, 0.18099480867385864, 0.2005157768726349, 0.17898377776145935, 0.7971988320350647, 0.8485375046730042, 0.8248836398124695, 0.8194207549095154, 0.8061084151268005, 0.8059894442558289, 0.7958412170410156, 0.8038275241851807, 0.784576952457428, 0.7772302031517029, 0.7732946872711182, 0.7853847146034241, 0.7543483972549438, 0.7688271999359131, 0.7609366178512573, 0.7614707946777344, 0.7627699971199036, 0.7605279088020325, 0.7597358226776123, 0.7428140640258789, 0.4477619528770447, 0.4640714228153229, 0.449712872505188]
intensities: [1.2912776020692121e+22, 1.2912776020692121e+22, 1.2912776020692121e+22, 1.2912776020692121e+22, 1.2912776020692121e+22, 1.2912776020692121e+22, 1.2912776020692121e+22, 1.2912776020692121e+22, 1.2912776020692121e+22, 1.2912776020692121e+22, 1.2912776020692121e+22, 1.2912776020692121e+22, 1.2912776020692121e+22, 1.2912776020692121e+22, 1.2912776020692121e+22, 1.2912776020692121e+22, 1.2912776020692121e+22, 1.2912776020692121e+22, 1.2912776020692121e+22, 1.2912776020692121e+22, 1.2912776020692121e+22, 1.2912776020692121e+22, 1.2912776020692121e+22, 1.2912776020692121e+22, 1.2912776020692121e+22, 1.2912776020692121e+22, 1.2912776020692121e+22, 1.2912776020692121e+22, 1.2912776020692121e+22, 1.2912776020692121e+22, 1.2912776020692121e+22, 1.2912776020692121e+22, 5.324934164434305e-44, 5.324934164434305e-44, 5.324934164434305e-44, 5.324934164434305e-44, 5.324934164434305e-44, 5.324934164434305e-44, 5.324934164434305e-44, 5.324934164434305e-44, 5.324934164434305e-44, 5.324934164434305e-44, 5.324934164434305e-44, 5.324934164434305e-44, 5.324934164434305e-44, 5.324934164434305e-44, 5.324934164434305e-44, 5.324934164434305e-44, 5.324934164434305e-44, 5.324934164434305e-44, 5.324934164434305e-44, 5.324934164434305e-44, 5.324934164434305e-44, 5.324934164434305e-44, 5.324934164434305e-44, 5.324934164434305e-44, 5.324934164434305e-44, 5.324934164434305e-44, 5.324934164434305e-44, 7.097552316265888e+22, 7.097552316265888e+22, 7.097552316265888e+22, 7.097552316265888e+22, 7.097552316265888e+22, 7.097552316265888e+22, 7.097552316265888e+22, 7.097552316265888e+22, 7.097552316265888e+22, 7.097552316265888e+22, 7.097552316265888e+22, 7.097552316265888e+22, 7.097552316265888e+22, 7.097552316265888e+22, 7.097552316265888e+22, 7.097552316265888e+22, 7.097552316265888e+22, 7.097552316265888e+22, 7.097552316265888e+22, 7.097552316265888e+22, 9.41672568026277e-43, 9.41672568026277e-43, 9.41672568026277e-43, 9.41672568026277e-43, 9.41672568026277e-43, 9.41672568026277e-43, 9.41672568026277e-43, 9.41672568026277e-43, 1.1289185274311598e+27, 1.1289185274311598e+27, 1.1289185274311598e+27, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.460415968814981e-38, 2.002220011746955e-19, 2.002220011746955e-19, 2.002220011746955e-19, 2.002220011746955e-19, 2.002220011746955e-19, 2.002220011746955e-19, 4.544942111731363e+30, 4.544942111731363e+30, 4.544942111731363e+30, 4.544942111731363e+30, 4.544942111731363e+30, 4.544942111731363e+30, 4.544942111731363e+30, 4.544942111731363e+30, 4.544942111731363e+30, 4.544942111731363e+30, 4.544942111731363e+30, 4.544942111731363e+30, 4.544942111731363e+30, 4.544942111731363e+30, 4.544942111731363e+30, 4.544942111731363e+30, 4.544942111731363e+30, 4.544942111731363e+30, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.1811024326731295e-38, 4.1811024326731295e-38, 4.1811024326731295e-38, 4.1811024326731295e-38, 4.1811024326731295e-38, 4.1811024326731295e-38, 4.1811024326731295e-38, 4.1811024326731295e-38, 4.1811024326731295e-38, 1.1210387714598537e-42, 9.80908925027372e-45, 9.80908925027372e-45, 9.80908925027372e-45, 9.80908925027372e-45, 9.80908925027372e-45, 9.80908925027372e-45, 9.80908925027372e-45, 4.118867553092e-33, 4.118867553092e-33, 3.0600612751156956e+32, 3.0600612751156956e+32, 3.0600612751156956e+32, 3.0600612751156956e+32, 3.0600612751156956e+32, 3.0600612751156956e+32, 3.0600612751156956e+32, 3.0600612751156956e+32, 3.0600612751156956e+32, 3.0600612751156956e+32, 3.0600612751156956e+32, 3.587324068671532e-43, 3.587324068671532e-43, 4.3063059348946493e+21, 4.3063059348946493e+21, 4.3063059348946493e+21, 4.3063059348946493e+21, 4.3063059348946493e+21, 4.3063059348946493e+21, 4.3063059348946493e+21, 4.3063059348946493e+21, 4.3063059348946493e+21, 4.3063059348946493e+21, 4.3063059348946493e+21, 4.3063059348946493e+21, 4.3063059348946493e+21, 4.3063059348946493e+21, 4.3063059348946493e+21, 4.322528199925419e-38, 4.322528199925419e-38, 4.322528199925419e-38, 4.322528199925419e-38, 4.322528199925419e-38, 4.322528199925419e-38, 4.322528199925419e-38, 4.322528199925419e-38, 4.322528199925419e-38, 4.322528199925419e-38, 4.322528199925419e-38, 4.322528199925419e-38, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 6.06147188484565e-33, 6.06147188484565e-33, 6.06147188484565e-33, 6.06147188484565e-33, 6.06147188484565e-33, 6.06147188484565e-33, 4.1571391078944036e-38, 4.1571391078944036e-38, 4.1571391078944036e-38, 4.1571391078944036e-38, 4.1571391078944036e-38, 4.1571391078944036e-38, 4.1571391078944036e-38, 8.407790785948902e-45, 8.407790785948902e-45, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.633899241035629e-39, 4.633899241035629e-39, 4.633899241035629e-39, 4.633899241035629e-39, 0.0, 0.0, 0.0, 0.0, 3.939575277232831e-33, 3.939575277232831e-33, 3.939575277232831e-33, 3.939575277232831e-33, 3.939575277232831e-33, 3.939575277232831e-33, 1.1210387714598537e-42, 1.1210387714598537e-42, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 8.407790785948902e-45, 8.407790785948902e-45, 8.407790785948902e-45, 8.407790785948902e-45, 4.035739577255473e-43, 4.035739577255473e-43, 4.035739577255473e-43, 4.035739577255473e-43, 4.434111915081447e-38, 4.434111915081447e-38, 4.434111915081447e-38, 4.434111915081447e-38, 4.434111915081447e-38, 4.434111915081447e-38, 4.434111915081447e-38, 4.434111915081447e-38, 4.434111915081447e-38, 4.434111915081447e-38, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 3.9830156709674684e-33, 4.04313045206852e-33, 1.793662034335766e-43, 1.793662034335766e-43, 1.793662034335766e-43, 1.793662034335766e-43, 1.793662034335766e-43, 1.793662034335766e-43, 1.793662034335766e-43, 1.793662034335766e-43, 1.793662034335766e-43, 1.793662034335766e-43, 1.793662034335766e-43, 1.793662034335766e-43, 1.793662034335766e-43, 1.793662034335766e-43, 1.793662034335766e-43, 1.793662034335766e-43, 1.793662034335766e-43, 1.793662034335766e-43, 1.793662034335766e-43, 1.2912776020692121e+22, 1.2912776020692121e+22, 1.2912776020692121e+22]
---

```

8. Please, describe detailedly what difficulty you are in 

   i found the lds doesn't have some scan ranges data in testing the [maze-solution](https://github.com/EndlessLoops/fira_maze/blob/master/script/maze_explorer.py)

```
def scan_callback(msg):
    global range_front
    global range_right
    global range_left
    global ranges
    global min_front,i_front, min_right,i_right, min_left ,i_left
    
    ranges = msg.ranges
    # get the range of a few points
    # in front of the robot (between 5 to -5 degrees)
    range_front[:5] = msg.ranges[5:0:-1]  
    range_front[5:] = msg.ranges[-1:-5:-1]
    # to the right (between 300 to 345 degrees)
    range_right = msg.ranges[300:345]
    # to the left (between 15 to 60 degrees)
    range_left = msg.ranges[60:15:-1]
    # get the minimum values of each range 
    # minimum value means the shortest obstacle from the robot
    min_range,i_range = min( (ranges[i_range],i_range) for i_range in xrange(len(ranges)) )
    min_front,i_front = min( (range_front[i_front],i_front) for i_front in xrange(len(range_front)) )
    min_right,i_right = min( (range_right[i_right],i_right) for i_right in xrange(len(range_right)) )
    min_left ,i_left  = min( (range_left [i_left ],i_left ) for i_left  in xrange(len(range_left )) )

```

and it can work in gazebo and lds can feedback related scan range data .when i work in the real tb3 , /scan can't publish some range data ,like  `2.2079999446868896, 0.0, 0.0, 0.0, 2.5339999198913574, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2.5859999656677246, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.100000023841858, 0.9559999704360962, 0.9559999704360962, 0.8899999856948853,`

I want to know what problems in here ? 

I look forward to and sincerely thank you for your reply.
