### ISSUE TITLE
Mapless Move Base Problem

### ISSUE THREAD

**Issue by bektaskemal** [ROBOTIS-GIT/turtlebot3#611]
ISSUE TEMPLATE ver. 0.3.0

1. Which TurtleBot3 you have?
My problem is on simulation but I tried all of them.

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [X] ROS 1 Melodic Morenia
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] etc (PLEASE, WRITE DOWN YOUR ROS VERSION HERE)

3. Which SBC(Single Board Computer) is working on TurtleBot3?
   -
4. Which OS you installed in SBC?
  - 

5. Which OS you installed in Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [X] Ubuntu 18.04 LTS (Bionic Beaver)
    - [ ] Linux Mint 18.x
    - [ ] Linux Mint 19.x
    - [ ] etc (PLEASE, WRITE DOWN YOUR OS)

6. Write down software version and firmware version

    - Software version:  [x.x.x]

    - Firmware version: [x.x.x]

7. Write down the commands you used in order

    - launch gazebo world with turtlebot
    - launch tf publisher 
    - launch move_base

8. Copy and Paste your error message on terminal

    - No error

9. Please, describe detailedly what difficulty you are in

    - I am trying to use move_base without map. But costmap doesn't use laserscan in front of the robot and only detects obstacles in the back. You can see it in image below:
![Screenshot from 2020-07-08 17-29-03](https://user-images.githubusercontent.com/34746077/86931266-90d27200-c140-11ea-9cd6-86ec3e1be598.png)
    - Move_base launch file: 
<launch>

  <arg name="no_static_map" default="true"/>

  <arg name="base_global_planner" default="global_planner/GlobalPlanner"/>
  <arg name="base_local_planner" default="dwa_local_planner/DWAPlannerROS"/>

  <node pkg="move_base" type="move_base" respawn="false" name="move_base" output="screen">

    <param name="base_global_planner" value="$(arg base_global_planner)"/>
    <param name="base_local_planner" value="$(arg base_local_planner)"/>  
    <rosparam file="$(find turtlebot3_navigation)/param/planner.yaml" command="load"/>

    
    <rosparam file="$(find turtlebot3_navigation)/param/costmap_common.yaml" command="load" ns="global_costmap" />
    <rosparam file="$(find turtlebot3_navigation)/param/costmap_common.yaml" command="load" ns="local_costmap" />

    
    <rosparam file="$(find turtlebot3_navigation)/param/costmap_local.yaml" command="load" ns="local_costmap" />
    <param name="local_costmap/width" value="10.0"/>
    <param name="local_costmap/height" value="10.0"/>

    
    <rosparam file="(find turtlebot3_navigation)/param/costmap_global_static2.yaml" command="load" ns="global_costmap" unless="$(arg no_static_map)"/>
    
    
    <rosparam file="$(find turtlebot3_navigation)/param/costmap_global_laser.yaml" command="load" ns="global_costmap" if="$(arg no_static_map)"/>
    <param name="global_costmap/width" value="100.0" if="$(arg no_static_map)"/>
    <param name="global_costmap/height" value="100.0" if="$(arg no_static_map)"/>
  </node>

</launch>

Params:
```
footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.01

robot_base_frame: base_footprint
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.1

obstacle_range: 7.5
raytrace_range: 6.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {sensor_frame: base_footprint, data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

inflation:
    inflation_radius: 0.5

global_frame: odom
rolling_window: true

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}

global_frame: odom
rolling_window: true
track_unknown_space: true

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}

```

Planner:
```
controller_frequency: 10.0
recovery_behaviour_enabled: false

NavfnROS:
  allow_unknown: true # Specifies whether or not to allow navfn to create plans that traverse unknown space.
  default_tolerance: 0.1 # A tolerance on the goal point for the planner.


DWAPlannerROS:
  # Robot configuration parameters  
  acc_lim_x: 2.5
  acc_lim_y: 0
  acc_lim_th: 2.2

  max_vel_x: 1.0
  min_vel_x: -0.1
  max_vel_y: 0
  min_vel_y: 0

  max_vel_trans: 0.5
  min_vel_trans: 0.1
  max_vel_theta: 1.0
  min_vel_theta: 0.2

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.2

  # # Forward Simulation Parameters
  # sim_time: 2.0
  # sim_granularity: 0.025
  # vx_samples: 3
  # vy_samples: 0
  # vtheta_samples: 20
  # penalize_negative_x: true

  # # Trajectory scoring parameters
  # path_distance_bias: 32.0 # The weighting for how much the controller should stay close to the path it was given
  # goal_distance_bias: 24.0 # The weighting for how much the controller should attempt to reach its local goal, also controls speed
  # occdist_scale: 255 # The weighting for how much the controller should attempt to avoid obstacles
  # forward_point_distance: 0.325 # The distance from the center point of the robot to place an additional scoring point, in meters
  # stop_time_buffer: 0.2  # The amount of time that the robot must stThe absolute value of the veolicty at which to start scaling the robot's footprint, in m/sop before a collision in order for a trajectory to be considered valid in seconds
  # scaling_speed: 0.25 # The absolute value of the veolicty at which to start scaling the robot's footprint, in m/s
  # max_scaling_factor: 0.2 # The maximum factor to scale the robot's footprint by

  # # Oscillation Prevention Parameters
  # oscillation_reset_dist: 0.25 #How far the robot must travel in meters before oscillation flags are reset (double, default: 0.05)

```
