### ISSUE TITLE
GPS with turtlebot3

### ISSUE THREAD

**Issue by YXGuan** [ROBOTIS-GIT/turtlebot3#900]
ISSUE TEMPLATE ver. 0.4.0

1. Which TurtleBot3 platform do you use?

    - [X] Burger
    - [ ] Waffle
    - [ ] Waffle Pi

2. Which ROS is working with TurtleBot3?

    - [ ] ROS 1 Kinetic Kame
    - [ ] ROS 1 Melodic Morenia
    - [X] ROS 1 Noetic Ninjemys
    - [ ] ROS 2 Dashing Diademata
    - [ ] ROS 2 Eloquent Elusor
    - [ ] ROS 2 Foxy Fitzroy
    - [ ] etc (Please specify your ROS Version here)

3. Which SBC(Single Board Computer) is working on TurtleBot3?

    - [ ] Intel Joule 570x
    - [ ] Raspberry Pi 3B+
    - [X] Raspberry Pi 4
    - [ ] etc (Please specify your SBC here)

4. Which OS you installed on SBC?

    - [X] Raspbian distributed by ROBOTIS
    - [ ] Ubuntu MATE (16.04/18.04/20.04)
    - [ ] Ubuntu preinstalled server (18.04/20.04)
    - [ ] etc (Please specify your OS here)

5. Which OS you installed on Remote PC?

    - [ ] Ubuntu 16.04 LTS (Xenial Xerus)
    - [ ] Ubuntu 18.04 LTS (Bionic Beaver)
    - [X] Ubuntu 20.04 LTS (Focal Fossa)
    - [ ] Windows 10
    - [ ] MAC OS X (Specify version)
    - [ ] etc (Please specify your OS here)

6. Specify the software and firmware version(Can be found from Bringup messages)

    - Software version: [x.x.x]
    - Firmware version: [1.2.6]

7. Specify the commands or instructions to reproduce the issue.
I installed nmea_navsat_driver on turtlebot sudo apt-get install ros-noetic-nmea-navsat-driver
    - sudo chmod 777 /dev/ttyUSB1
    - rosrun nmea_navsat_driver nmea_serial_driver _port:=ttyUSB1 _baud:=9600
    - roslaunch turtlebot3_bringup turtlebot3_robot.launch

8. Copy and Paste the error messages on terminal.

    Expect to have a GPS/Fix, but actually have no readings

9. Please describe the issue in detail.

    Hi there, I would appreciate some help for setting up a GPS sensor with Turtlebot3. Thank you
Do I need to modify the turtlebot_bringup file?

    It can see the USB port but there's no readings

![image](https://user-images.githubusercontent.com/55643200/184989404-e539d4f5-b8bd-4a58-a106-92eeae832a87.png)

![GPS_turtlebot](https://user-images.githubusercontent.com/55643200/185723007-f4b14616-f5e9-405e-a603-28a74bdc6701.jpg)

**Comment by YXGuan** [comment]
The above question has been resolved. However I got a new question, does Turtlebot3 come with a magnetic field sensor? ( or only IMU?) 
```

magnetic_field_covariance: [0.004800000227987766, 0.0, 0.0, 0.0, 0.004800000227987766, 0.0, 0.0, 0.0, 0.004800000227987766] 

--- 

header:  

  seq: 70 

  stamp:  

    secs: 1660339774 

    nsecs: 447851036 

  frame_id: "mag_link" 

magnetic_field:  

  x: 0.0 

  y: 0.0 

  z: 0.0 
```
